kind: Sync
apiVersion: nomos.dev/v1alpha1
metadata:
  name: rbac
spec:
  groups:
  - group: rbac.authorization.k8s.io
    kinds:
    - kind: ClusterRole
      versions:
      - version: v1
        compareFields:
        - rules
    - kind: ClusterRoleBinding
      versions:
      - version: v1
        compareFields:
        - subjects
        - roleRef
    - kind: Role
      versions:
      - version: v1
        compareFields:
        - rules
    - kind: RoleBinding
      versions:
      - version: v1
        compareFields:
        - subjects
        - roleRef
